/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RegisterViewController;

import LoginViewController.Login;
import java.awt.Color;
import org.jdesktop.swingx.border.DropShadowBorder;

/**
 *
 * @author HP
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new RegisterViewController.Background();
        pnRegister = new javax.swing.JPanel();
        lblRegister = new javax.swing.JLabel();
        imgRegister = new RegisterViewController.RegisterIcon();
        tfLastName = new javax.swing.JTextField();
        tfUserName = new javax.swing.JTextField();
        tfFirstName = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        button1 = new CustomButton.Button();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnRegister.setOpaque(false);

        lblRegister.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRegister.setText("Register");
        lblRegister.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblRegister.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        tfLastName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfLastName.setText("Last Name");
        tfLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfLastNameFocusLost(evt);
            }
        });

        tfUserName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfUserName.setText("Username");
        tfUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUserNameFocusLost(evt);
            }
        });

        tfFirstName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfFirstName.setText("First Name");
        tfFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfFirstNameFocusLost(evt);
            }
        });

        tfPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfPassword.setText("Password");
        tfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPasswordFocusLost(evt);
            }
        });
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(0, 102, 153));
        button1.setText("Register");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Already have an account?");

        btnLogin.setText("Login");
        btnLogin.setBorderPainted(false);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnRegisterLayout = new javax.swing.GroupLayout(pnRegister);
        pnRegister.setLayout(pnRegisterLayout);
        pnRegisterLayout.setHorizontalGroup(
            pnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegisterLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(pnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRegisterLayout.createSequentialGroup()
                        .addGroup(pnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnRegisterLayout.createSequentialGroup()
                                .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfUserName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnRegisterLayout.createSequentialGroup()
                                .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(imgRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(pnRegisterLayout.createSequentialGroup()
                        .addGroup(pnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnRegisterLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnRegisterLayout.setVerticalGroup(
            pnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRegisterLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(tfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnLogin))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        background1.add(pnRegister);
        pnRegister.setBounds(80, 50, 1070, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, 1214, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void tfFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFirstNameFocusGained
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShadowColor(Color.BLUE);
        shadow.setShadowSize(5); // Size of the shadow
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowTopShadow(true);
        shadow.setShowBottomShadow(true);
        tfFirstName.setBorder(shadow);
        
        String defaultString="First Name";
        if (tfFirstName.getText().equals(defaultString)){
            tfFirstName.setText("");
            tfFirstName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfFirstNameFocusGained

    private void tfFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFirstNameFocusLost
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShadowColor(Color.BLACK);
        shadow.setShadowSize(3); // Size of the shadow
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowTopShadow(true);
        shadow.setShowBottomShadow(true);
        tfFirstName.setBorder(shadow);
        
        String defaultString="First Name";
        if (tfFirstName.getText().equals("")){
            tfFirstName.setText(defaultString);
            tfFirstName.setForeground(new Color(60,60,60));

        }
    }//GEN-LAST:event_tfFirstNameFocusLost

    private void tfLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLastNameFocusGained
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShadowColor(Color.BLUE);
        shadow.setShadowSize(5); // Size of the shadow
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowTopShadow(true);
        shadow.setShowBottomShadow(true);
        tfLastName.setBorder(shadow);
        
        String defaultString="Last Name";
        if (tfLastName.getText().equals(defaultString)){
            tfLastName.setText("");
            tfLastName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfLastNameFocusGained

    private void tfLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLastNameFocusLost
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShadowColor(Color.BLACK);
        shadow.setShadowSize(3); // Size of the shadow
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowTopShadow(true);
        shadow.setShowBottomShadow(true);
        tfLastName.setBorder(shadow);
        
        String defaultString="Last Name";
        if (tfLastName.getText().equals("")){
            tfLastName.setText(defaultString);
            tfLastName.setForeground(new Color(60,60,60));

        }
    }//GEN-LAST:event_tfLastNameFocusLost

    private void tfUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserNameFocusGained
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShadowColor(Color.BLUE);
        shadow.setShadowSize(5); // Size of the shadow
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowTopShadow(true);
        shadow.setShowBottomShadow(true);
        tfUserName.setBorder(shadow);
        
        String defaultString="Username";
        if (tfUserName.getText().equals(defaultString)){
            tfUserName.setText("");
            tfUserName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_tfUserNameFocusGained

    private void tfUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUserNameFocusLost
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShadowColor(Color.BLACK);
        shadow.setShadowSize(3); // Size of the shadow
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowTopShadow(true);
        shadow.setShowBottomShadow(true);
        tfUserName.setBorder(shadow);
        
        String defaultString="Usename";
        if (tfUserName.getText().equals("")){
            tfUserName.setText(defaultString);
            tfUserName.setForeground(new Color(60,60,60));

        }
    }//GEN-LAST:event_tfUserNameFocusLost

    private void tfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusGained
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShadowColor(Color.BLUE);
        shadow.setShadowSize(5); // Size of the shadow
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowTopShadow(true);
        shadow.setShowBottomShadow(true);
        tfPassword.setBorder(shadow);
        
        String defaultString="Password";
        if (tfPassword.getText().equals(defaultString)){
            tfPassword.setText("");
            tfPassword.setForeground(Color.BLACK);
            tfPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_tfPasswordFocusGained

    private void tfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusLost
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShadowColor(Color.BLACK);
        shadow.setShadowSize(3); // Size of the shadow
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowTopShadow(true);
        shadow.setShowBottomShadow(true);
        tfPassword.setBorder(shadow);
        
        String defaultString="Password";
        if (tfPassword.getText().equals("")){
            tfPassword.setText(defaultString);
            tfPassword.setForeground(new Color(60,60,60));
            tfPassword.setEchoChar((char)0 );
        }
    }//GEN-LAST:event_tfPasswordFocusLost

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        new Login();
        this.dispose();
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void init(){
        DropShadowBorder shadow = new DropShadowBorder();
        shadow.setShadowColor(Color.BLACK);
        shadow.setShadowSize(6); // Size of the shadow
        shadow.setShowLeftShadow(true);
        shadow.setShowRightShadow(true);
        shadow.setShowTopShadow(true);
        shadow.setShowBottomShadow(true);
        pnRegister.setBorder(shadow);
        
        
        DropShadowBorder shadow1 = new DropShadowBorder();
        shadow1.setShadowColor(Color.BLACK);
        shadow1.setShadowSize(3); // Size of the shadow
        shadow1.setShowLeftShadow(true);
        shadow1.setShowRightShadow(true);
        shadow1.setShowTopShadow(true);
        shadow1.setShowBottomShadow(true);
       
        tfFirstName.setBackground(new Color(0,0,0,0));
        tfFirstName.setBorder(shadow1);
        tfLastName.setBackground(new Color(0,0,0,0));
        tfLastName.setBorder(shadow1);
        tfUserName.setBackground(new Color(0,0,0,0));
        tfUserName.setBorder(shadow1);
        tfPassword.setBackground(new Color(0,0,0,0));
        tfPassword.setBorder(shadow1);
        
        tfFirstName.setForeground(new Color(60,60,60));
        tfLastName.setForeground(new Color(60,60,60));
        tfUserName.setForeground(new Color(60,60,60));
        tfPassword.setForeground(new Color(60,60,60));
        tfPassword.setEchoChar((char)0 );
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        
        btnLogin.setBackground(new Color(0,0,0,0));
        btnLogin.setForeground(new Color(0,0,139));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RegisterViewController.Background background1;
    private javax.swing.JButton btnLogin;
    private CustomButton.Button button1;
    private RegisterViewController.RegisterIcon imgRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JPanel pnRegister;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfLastName;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUserName;
    // End of variables declaration//GEN-END:variables
}
